(require 'cl)
(add-to-list 'load-path "~/.emacs.d/")
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/.emacs.d//ac-dict")
(ac-config-default)
(require 'clojure-mode)
(add-hook 'clojure-mode-hook (lambda () (paredit-mode +1)))
(add-to-list 'auto-mode-alist '("\\.cljs$" . clojure-mode))
(require 'paredit)
(define-key paredit-mode-map (kbd "C-M-a") 'backward-up-list)
(define-key paredit-mode-map (kbd "C-M-e") 'up-list)
(require 'ac-nrepl)
(add-hook 'nrepl-mode-hook 'ac-nrepl-setup)
(add-hook 'nrepl-interaction-mode-hook 'ac-nrepl-setup)
(eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'nrepl-mode))
(provide 'dj)
